version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions-updates:
        applies-to: version-updates
        patterns: ["*"]
      github-actions-security-updates:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    # versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      uv-version-updates:
        applies-to: version-updates
        patterns: ["*"]
      uv-security-updates:
        applies-to: security-updates
        patterns: ["*"]
