version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
sphinx:
  configuration: docs/source/conf.py
formats:
  - pdf
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
